spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdeed
    username: postgres
    password: dupa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 28472D4B6150645367566B5970337336763979244226452948404D6251655468
  expirationInMinutes: 1440